--!strict

-- Notes 9/7/25
-- Slarea has been renamed to Pulse. Slarea as a name I felt to not be representative
-- at all of the function that this library provides, which is a tool made to allow people to
-- get an understanding of how their code is functioning; similar to a doctor feeling for a pulse
-- or having an EKG done. 

-- Pulse allows insights which are deeper then conventional debugging or logging methods
-- in that you gain the ability to detect in real time irregularities that may exist in your code
-- and pinpoint problems sooner

-- These insights gained through Pulse then allow for further optimization and improvement
-- upon your codebase as a whole

return nil
